[tool.poetry]
name = "hw27"
version = "0.1.0"
description = ""
authors = ["danilmirosh <miroshnichenko@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
